### ISSUE TITLE
L10N bot in gnome and transifex ?!

### ISSUE THREAD

**Issue by Jibec** [hughsie/appstream-glib#120]
hi, I'm confused ... Where should we work ? Fedora left transifex because it's not open-source. 
Please only keep https://l10n.gnome.org/module/appstream-glib/ as we already can find appstream, and delete all transifex reference so contributors don't get confuse.

thanks for your help

**Comment by hughsie** [comment]
Well, I know we used to use https://www.transifex.com/freedesktop/appstream-glib -- but I'm not sure what I should be using now. Ideas welcome!

**Comment by ignatenkobrain** [comment]
zanata.

https://fedoraproject.org/wiki/L10N_Move_To_Zanata

**Comment by hughsie** [comment]
So zanata seems kinda Fedora specific; that would be the wrong message entirely for people contributing to appstream-glib.

**Comment by hughsie** [comment]
So i guess I could give zantana a try; does anyone feel like submitting a patch?

**Comment by ignatenkobrain** [comment]
@hughsie I could do, but tomorrow

**Comment by Jibec** [comment]
!?!

you have a great community of translators in l10n.gnome where we already can find appstream, we know what is translated and what isn't, it isn't distro-related, why would you go somewhere else ?

sincerely, Zanata is nice looking and translation memory is great, but a pain for community management or quality monitoring (see changes, what happened, etc.).

**Comment by Super-Baleine** [comment]
I think, if there's more contributors at l10n.gnome, then keep the gnome repository ans delete all transifex reference, and tell to the contributors of Fedora to go on the gnome repository...

**Comment by hughsie** [comment]
@Jibec but appstream-glib isn't a GNOME project...

**Comment by Super-Baleine** [comment]
So, why appstream-glib is on the GNOME Project ?

**Comment by hughsie** [comment]
No idea at all.

**Comment by Super-Baleine** [comment]
Okay...

**Comment by afranke** [comment]
It is not "on the GNOME Project". We have a set of external dependencies on Damned lies. Their translations are handled upstream on another platform, but we want to keep track of their status and possibly push some work on them. When we do contribute to those, we generally first use our usual workflow on Damned lies, thus ensuring quality, and then we upload to the external platform instead of committing through Damned lies. This is explained at the top of https://l10n.gnome.org/vertimus/appstream-glib/master/po/fr for instance. Everything is fine, don't panic. This can safely be CLOSED NOTABUG.

**Comment by hughsie** [comment]
I've moved things to Zanata: https://fedora.zanata.org/project/view/appstream-glib

**Comment by Jibec** [comment]
hi there, you should update your readme and close your project in Zanata (I see recent work, you may merge po files and push it to back Zanata)
