### ISSUE TITLE
Omitting ".desktop" suffix is allowed

### ISSUE THREAD

**Issue by jnumm** [hughsie/appstream-glib#146]
This is the same bug as ximion/appstream#100.
If the id of a desktop application does not end in ".desktop", appstream-util validate will complain `<id> does not have correct extension for kind`. That is incorrect as the specification tells us
>[For applications, the <id/> tag value must be the same name as the installed .desktop file for the application, the .desktop suffix of the filename may be omitted.](https://www.freedesktop.org/software/appstream/docs/sect-Metadata-Application.html)

Omitting the ".desktop" suffix is not an error.
A relevant line: https://github.com/hughsie/appstream-glib/blob/master/libappstream-glib/as-app-validate.c#L1111

**Comment by hughsie** [comment]
Whilst I agree that in the spec it says that, a good proportion of the tools that generate and consume AppStream XML will currently break if you omit the .desktop suffix. I was talking to @ximion yesterday about this, and we need more details in the specification to deal with when the application ID does not match the appstream ID. Until we've got it sorted out in the spec, and a good majority of tools don't break, I think including the .desktop in the <id> is a very good idea.

**Comment by ximion** [comment]
@hughsie The spec is fine and this change has been in production at Debian for almost a year without noticeable breakage - the only thing that is potentially broken is launching such apps in GNOME Software, all other tools using libappstream are fine (since libas had a `get_desktop_id()` method for that purpose for a very long time).

So, I think this is a safe change, if done right with appropriate fallback code.

That being said, I still would like to have an explicit tag in AppStream to specify a way to launch apps (by command, dbus-activation or desktop-id), to get rid of some automagic and to support the case of desktop-app components not having a directly associated launchable .desktop file (or multiple files, for that matter - think of software suites (rare, but they exist)).

**Comment by hughsie** [comment]
Okay, I'm fine with removing the validation warning. I'm not fine removing the validation warning before we talk about XML API on how to launch apps.

**Comment by ximion** [comment]
Getting the `launchable` proposal through would solve this issue in a very nice way ( https://lists.freedesktop.org/archives/appstream/2017-March/000148.html ) ;-)

**Comment by hughsie** [comment]
Right, this depends on that.

**Comment by ximion** [comment]
It's solved now... ;-)
