### ISSUE TITLE
compile failure in as-tag.c

### ISSUE THREAD

**Issue by RemiCardona** [hughsie/appstream-glib#148]
```
In file included from as-tag.c:41:0:
as-tag-private.h: In function ‘_as_tag_hash’:
as-tag-private.h:81:32: warning: conversion to ‘unsigned int’ from ‘size_t {aka long unsigned int}’ may alter its value [-Wconversion]
   register unsigned int hval = len;
                                ^
as-tag-private.h: At top level:
as-tag-private.h:220:1: error: conflicting types for ‘_as_tag_from_gperf’
 _as_tag_from_gperf (register const char *str, register size_t len)
 ^
as-tag.c:40:26: note: previous declaration of ‘_as_tag_from_gperf’ was here
   const struct tag_data *_as_tag_from_gperf (const char *tag, guint etag);
                          ^
make[3]: *** [Makefile:1202: libappstream_glib_la-as-tag.lo] Error 1
make[3]: *** Waiting for unfinished jobs....
```

https://bugs.gentoo.org/show_bug.cgi?id=604888

```
gcc --version
gcc (Gentoo 5.4.0-r2 p1.2, pie-0.6.5) 5.4.0
```

Let me know if you need more info from me or one of the other reporters in the downstream Gentoo bug report.

Thanks

**Comment by gagern** [comment]
The [definition in the C file](https://github.com/hughsie/appstream-glib/blob/4d41eb637f346ee02256553c28fbf103b4a02e44/libappstream-glib/as-tag.c#L38-L42) says:

```c
#ifdef HAVE_GPERF
  /* we need to define this now as gperf just writes a big header file */
  const struct tag_data *as_tag_from_gperf (const char *tag, guint etag);
  #include "as-tag-private.h"
#endif
```

However it looks as though the gperf used here, namely 3.1 on my system, were defining that function just fine, so it should be possible to drop the definition here and just include the gperf-generated header. I'm also confused by the fact that the second argument is called `etag`, the same as one of the data items apparently associated with each tag in the `tag_data` structure.

Commenting out the definition, the package compiled finr for me.

**Comment by smcv** [comment]
The thing ending with a semicolon is a declaration, not a definition. gperf always generates a definition (body, with `{}`) for the function. Having a declaration for every extern function is a good idea, because that allows use of `gcc -Werror=missing-declarations` which semi-frequently finds bugs.

gperf 3.1 is very new (this year, when the previous release was in 2009). Looking at <http://git.savannah.gnu.org/cgit/gperf.git/log/> the relevant change might be <http://git.savannah.gnu.org/cgit/gperf.git/commit/?id=a343f956096d23d0384510a6616ff0a36c22a691>. If so, then it would maybe work to invoke gperf with `--language=ANSI-C` or put `%language=ANSI-C` in its input, and change the declaration to match?

**Comment by mgorny** [comment]
@smcv, may I ask what kind of bugs are found by `-Werror=missing-declarations`? I'm curious since I haven't seen anyone rely on that before.

**Comment by smcv** [comment]
`-Werror=missing-declarations` finds functions that should have been static, but were accidentally extern (not declared in a relevant header), leading to unintended ABI (namespace pollution).

(It occasionally also finds functions that were meant to be public and hence extern, but were missing from a header file.)

**Comment by ignatenkobrain** [comment]
well, with gperf 3.1:
```
-char *in_word_set (register const char *str, register unsigned int len);
+char *in_word_set (register const char *str, register size_t len);
```
