### ISSUE TITLE
L10N - can you please explain "Add a provide to a source file" 

### ISSUE THREAD

**Issue by Jibec** [hughsie/appstream-glib#164]
Hi,

thanks to this documentation:
https://github.com/hughsie/appstream-glib/blob/master/libappstream-glib/as-provide.c#L22

we understand that the term "provides" from this string:
https://github.com/hughsie/appstream-glib/blob/master/client/as-util.c#L4349

means the same thing as "provides" in a DNF/RPM context.

What we don't understand in this context is what is provided to what? We would have expected a file to be added as a provide of a packet and not the other way around. We're probably missing what "source file" is in your context. Or maybe aren't we able to understand where/by whom the command "add-provide" may be used.

Can you please give us some help?

by the way, thank you for all the comments in your code.

**Comment by ximion** [comment]
> means the same thing as "provides" in a DNF/RPM context.

Maybe in spirit, but not literally.

Any code is probably not the right place to answer any questions about this, which is why we have a specification: https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-provides
(which reminds me that this section is a bit outdated and could use some updated working - it's still correct though)

**Comment by Jibec** [comment]
Great, thank you :)
