### ISSUE TITLE
attribute-invalid     : <release> timestamp is in the future

### ISSUE THREAD

**Issue by Jehan** [hughsie/appstream-glib#246]
I thought we discussed this already but can't find neither opened nor closed bug report, so… anyway!

Since our `<release>` tags is localized (as is our whole appdata file), we need to push it to our repo in advance and set a date in the future. But when `appstream-util` complains with:

```
desktop/org.gimp.GIMP.appdata.xml: FAILED:
• attribute-invalid     : <release> timestamp is in the future
Validation of files failed
```

If we set no date, or just TODO, the error becomes:

```
desktop/org.gimp.GIMP.appdata.xml: FAILED:
• attribute-missing     : <release> has no timestamp
Validation of files failed
```

This is annoying because it means we cannot prepare a release tag in advance and in the same time use `appstream-util` for unit-testing our appdata.

**Comment by hughsie** [comment]
psst: you also want to validate with `relax`. :)

**Comment by bochecha** [comment]
Fox those like me finding this issue later on and being puzzled:

* `appstream-util validate-relax` still complains about release dates being in the future;
* `appstream-util validate-relax` accepts releases without any dates;

**Comment by eszlari** [comment]
According to https://github.com/hughsie/appstream-glib/issues/153, this check was added because of gnome-software can't handle it. I guess this has not been fixes there yet.

This check is annoying for Krita too: new releases get tagged  a few days before the official release, e.g. 4.2.9 tagged today (2020-03-23), release will be Wednesday (2020-03-25), so I can't do a test build without disabling the appstream-util check.

**Comment by eszlari** [comment]
Maybe you could increase the allowed range to one week in the future?
