### ISSUE TITLE
appstream-util validate-strict: <li> cannot end in '.'

### ISSUE THREAD

**Issue by Jehan** [hughsie/appstream-glib#249]
Is it really necessary for validate-strict to go as far as checking finale points?
I even realized that if the list item has several points (i.e. likely several sentences), it accepts the finale point, but then refuses a finale point without any previous one.

I.e.: `<li>The software now does this.</li>` is refused yet `<li>The software now does this. It also does that.</li>` is accepted.

I think it is going a bit far into trying to guess the description intent.
Can't we just get rid of this check?

**Comment by hughsie** [comment]
It's a style thing. I think it's okay to enforce these kinds of rules so that all software looks cohesive.

**Comment by Jehan** [comment]
Ok as you see fit. I think it is very weird that the style is enforced by the software. I personally don't see a problem (like at all!) that not everyone writes with the same style (even for technical texts/release notes) and find uneasy that the format software is choosing on behalf of the people.

I won't lose sleep over it though, so if you insist, it's ok. You can just close.
I still want to give my opinion at least once in the hope that you might come to agree and remove the check. :-)

**Comment by ximion** [comment]
For that exact reason, this issue is only an INFO type priority when using `appstreamcli validate`, which doesn't cause the validation to fail but is still sufficiently annoying to make people address it. Any style stuff is has an info priority, while format issues are always errors or warnings.

For `appstream-util` if you only care about format validity, the `validate-relax` subcommand is for you. So, I do think the current behavior is fine, due to there being an option to only do format validation if one wishes to do so.
