### ISSUE TITLE
Add an option that checks for Flathub requirements

### ISSUE THREAD

**Issue by hadess** [hughsie/appstream-glib#263]
Not sure what to call it, but having appstream-compose fail with errors when an appdata file wouldn't be accepted by Flathub would be of interest:
- Check for launchable desktop-id presence
- Check for .desktop file validity (see https://github.com/hughsie/appstream-glib/pull/262 and https://github.com/flathub/org.freedesktop.Piper/issues/1#issuecomment-420446582)

etc.

**Comment by barthalion** [comment]
From things we "broke" often in past:

* Ensure `<description>` content is wrapped in `<p>`
* Ensure OARS section is present
* A warning if releases section is missing

**Comment by hughsie** [comment]
I'm hesitant to encode the flathub requirements into libappstrea-glib -- people are going to be preparing the flathub builds on their distro, and that's certainly not going to have the most up to date `appstream-util validate` -- and even if they're running `appstream-compose` from the sandbox the appstream-glib in the runtime they're using might be quite old still.

This really feels like it should be part of flatpack-builder, or even better as part of the flathub self tests that get run when you build the component for the first time.

**Comment by hadess** [comment]
> I'm hesitant to encode the flathub requirements into libappstrea-glib -- people are going to be preparing the flathub builds on their distro, and that's certainly not going to have the most up to date `appstream-util validate` -- and even if they're running `appstream-compose` from the sandbox the appstream-glib in the runtime they're using might be quite old still.

Those requirements are mostly the same ones as for making an app show up in GNOME Software.

> This really feels like it should be part of flatpack-builder, or even better as part of the flathub self tests that get run when you build the component for the first time.

Flatpak-builder doesn't parse the appdata files, but uses appstream-compose to merge metadata into the appdata files it will eventually serve.

I don't mind not having a "--flathub" option, but that would mean adding separate checks for each one of the common bugs above. I don't mind that, it would just mean more work. Given how much time I've spent on trying to fix a  one-character bug in the appdata file, I'd rather the tools warned me early rather than letting me send broken appdata files to flathub.

**Comment by ramcq** [comment]
> even if they're running appstream-compose from the sandbox the appstream-glib in the runtime they're using might be quite old still.

This isn't the case in practice, because flatpak-builder uses the appstream-utils from inside the runtime, we've had to aggressively upgrade it across all of the runtimes in order to deal with all fo the bugs that we've uncovered in Flathub/Flatpak. So, if Flathub came to rely on a new option, we would in practice just upgrade it in every runtime that Flathub supported.

Anyway: I absolutely second having some kind of "common" definition of what is needed by app stores / UIs, and encoding that in appstream-glib. Having something that's at least going to satisfy Flathub and GNOME Software is really likely to do most other things. We could get the Discover folks to glance over the list and suggest any additional changes, but I don't think we will encounter any real-world resistance having better tooling to improve the standard of appdata.

**Comment by ramcq** [comment]
https://gist.github.com/ramcq/f4be40c19d677a7deb40e29a834e0a4b is the script we had internally, although it runs on the composed appstreams rather than the app data input, it could provide a reference of the things which impact visibility/validity inside GNOME Software.

**Comment by jgarciao** [comment]
Icons (64×64px and 128×128px sizes) are required too in Flathub. "stock icons" are not supported (see  [this issue](https://github.com/flathub/org.gnome.font-viewer/issues/1)

I don't remember if it's enforced right now but `<project_license>` must be correctly specified in the app's appdata file.

More info at [Flathub's App requirements](https://github.com/flathub/flathub/wiki/App-Requirements)
