### ISSUE TITLE
appstream-util validate complains that there's no <name> when an <id> is present

### ISSUE THREAD

**Issue by phillipwood** [hughsie/appstream-glib#33]
Validating the [appdata file for sound-juicer](https://git.gnome.org/browse/sound-juicer/tree/data/appdata/sound-juicer.appdata.xml.in) with appstream-util 0.34 fails as it wants a `<name>` tag even though there is an `<id>` tag in the file. With appstream-util 0.30 it passes. The [documentation for `<name>`](http://www.freedesktop.org/software/appstream/docs/chap-Quickstart.html#sect-Quickstart-DesktopApps) says

>While this tag is requited for a generic component, for an application metainfo file it is not necessary, but only recommended. You can omit this tag if you want the software center to have the same strings as defined in the XDG desktop file. In some cases it might be required to have a different name in the app-store, but most appdata.xml files will not need this.

I don't know if the documentation is out of date and I should add a <name> tag or if appstream-glib validate is being overzealous.

**Comment by hughsie** [comment]
appstream-glib validate only looks at the .appdata.xml file, rather than the appdata and desktop file (which is what the real system does to achieve the fallback). What I do is just copy and paste the same name from the desktop file into <name> and then it just gets deduplicated for the translators.

**Comment by phillipwood** [comment]
Thanks, I'll add the tag then.
