### ISSUE TITLE
AppData "specification" could be more concrete

### ISSUE THREAD

**Issue by cbm755** [hughsie/appstream-glib#90]
## `<metadata_license/>`

> Permissible license codes include: ...

This makes it sound like there is some wiggle room.  I suggest adding "The complete list is found here [1]".  and link to the line in the master branch of your code.
## `<project_group/>`

> Known values include GNOME, KDE, XFCE, MATE and LXDE, although other umbrella projects
> like Yorba would make sense too. 

Currently there is a whitelist, so again I suggest explicitly linking to it "The whitelist of acceptable values is [2]".

I offer no opinion on whether a whitelist is good or bad, just that the above text implies its free form.

**Comment by cbm755** [comment]
*ping*  Is the source of the website in a different repo?  I could send a patch if you point me at it.

**Comment by ximion** [comment]
The problem is that we can not compile a (pretty massive) list of all permissive licenses, we can only give recommendations which upstream projects should ideally follow.
For the project_group tag there shouldn't be a list of "valid" entries, it's a limitation imposed by the specific appstream-glib implementation. But I could consider adding that to the official spec and only allow a specific list of values.
See https://www.freedesktop.org/software/appstream/docs/chap-Quickstart.html#sect-Quickstart-DesktopApps for the more detailed instructions with a link to the spec. If you spot issues there, you can report then to the AppStream project[1] directly.

IMHO the metadata_license issue can't be fixed, unless we define a list of "only these permissive licenses allowed" in the spec, and for the project_group thing it should be highlighted that only appstream-glib imposes restrictions on its values.

[1]: https://github.com/ximion/appstream

**Comment by cbm755** [comment]
Ummm, but you do have a list, in particular `<metadata_license/>` is only a few things.... (note its `metadata_license`, not the project itself).

I'm just trying to make the documentation match the reality: any changes to reality are someone else's problem ;-)  Right now, people (me) read the docs, assume its free-form, when its *not*.

**Comment by cbm755** [comment]
Just to be clear, I'm talking about the docs at https://people.freedesktop.org/~hughsient/appdata/ which I think needs clarification.

**Comment by ximion** [comment]
The thing is: What you are referring to is *not* the documentation - it is what Richard wrote initially before we added it to the official documentation at https://www.freedesktop.org/software/appstream/docs/
So, I would argue that asglib restricting the values in project_group is wrong, and that the docs are correct, especially since other implementations handle it this way.
I handle it the way that the spec on freedesktop.org is *always* right, and if implementations diverge from it, it's a bug.

@hughsie We need a discussion here ;-)
 * What is the reason for you restricting the values for project_group?
 * I do think that restricting the allowed values for metadata_license makes sense, simply because it allows to verify more easily that the licenses are permissive and gives upstream projects a clear hint on which values they need to put in there to make their app show up. If we don't restrict values, we might need to have AppStream metadata generators read from an online-registry of permissive OSI-approved licenses, or we run into the risk of having some licenses allowed by appstream-builder but not appstream-generator or vice versa. https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-metadata_license already has a reasonable list, but for the GFDL we need to make sure that we only allow its version without invariant sections, because the "pure" GFDL is considered non-free by Debian, and we will run into trouble when allowing the "bare" GFDL.
 * We should consider linking your page to the quickstart guide in the spec[1] or replacing it by that. TBH, your page has fewer words and therefore might be less frightening to the users, so IMHO it might make sense to just check if it follows the spec and add a link to the official fd.o spec on top for people who want to know more, instead of replacing that page or have it redirect.

[1]: https://www.freedesktop.org/software/appstream/docs/chap-Quickstart.html#sect-Quickstart-DesktopApps

**Comment by cbm755** [comment]
All that makes sense to me.  Basically, as long as I have *clear rules* which, if I follow them, my file will (a) validate with asglib and (b) appear in Gnome Software (et al).

FWIW, I think I agree about restricting metadata_license to a whitelist.

And I certainly gree that project_group should *not* have a whitelist.  That implies that there is no whitelist in the implementation of asglib and whatever else runs between me and Gnome Software as well.

> ... already has a reasonable list,

Please make sure you also take from asglib: in particular I went to some effort to get `FSFAP` in there.

**Comment by ximion** [comment]
> Please make sure you also take from asglib: in particular I went to some effort to get FSFAP in there.

That's the problem with whitelists ;-) There is always that one license someone wants which isn't yet in the allowed pool. But yeah, `FSFAP` seems very reasonable and it also makes sense to allow what asglib already allows, esp. since `appstream-generator` does not impose restrictions on the metadata_license field yet.

**Comment by hughsie** [comment]
I've relaxed the checks in appstream-glib for project_group, and have moved them to where they belong in gnome-software.
