### ISSUE TITLE
ArchLinux: appstream-builder doesn't extract data from packages that don't contain appdata

### ISSUE THREAD

**Issue by antonio-rojas** [hughsie/appstream-glib#93]
With recent versions of appstream-builder (at least since 0.5.5), data isn't extracted from .desktop files for packages that don't contain appdata info.

I'm using the following command to extract the data:

appstream-builder --api-version=0.7 --origin=archlinux --packages-dir={repo} --include-failed --enable-hidpi --basename=appstream

Used to work with 0.4

**Comment by hughsie** [comment]
Right, we need the AppData files now to construct the metadata. Just .desktop files are not enough.

**Comment by nqn76** [comment]
That's unfortunate... in Arch we provide vanilla upstream packages, and many of them (eg. firefox) don't provide appstream files

**Comment by colomar** [comment]
Is there a specific reason why extracting metadata from desktop files is not supported anymore?

**Comment by hughsie** [comment]
Well, the change was made for a few reasons:
 * Debian is doing the same thing
 * GNOME Software looks simply bad and can't provide require functionality without the extra data
 * It's been THREE YEARS since I started asking upstream software for AppData files
 * Including all the apps with desktop files in the metadata meant we had to keep a huge blacklist of things-that-are-not-really-apps to not show (e.g. launchers, dashes, docks, debug tools), now AppData == show in software center
 * The carrot of "being higher in the search results" has turned into a stick of "not showing up in the software center"

So far about 800 upstream projects have added AppData files, and now it's either the downstream's responsibility to convince upstream it's a good idea, or to patch in the extra file into the distro tarballs.

I really don't think you can provide a software center experience with just the application name, icon, package size and nothing else. Sooner or later you have to raise the bar, and that's been happening gradually since we started this initiative.

You can see the effect of this here: http://gs-stats.leuenberger.net/ -- basically you make the requirement higher and you see an uptick of AppData adoption. March last year was increasing the icon size requirement. November last year was making AppData files mandatory. OpenSuse ships older versions of some applications and not all upstream software but the same stats exist for Fedora, albeit not in as nice graphical form.
